### ISSUE TITLE
changing scoring?

### ISSUE THREAD

**Issue by salogel42** [fela/connect-everything#2]
I've basically given up playing the game because you have to devote such a large amount of time (beat levels 9-15) before you do anything that "counts", and then you don't even get to finish the level (VERY frustrating for me).

I'd personally strongly prefer keeping track of how much time each level takes and just scoring them independently, based on time, maybe with penalties for unnecessary moves, but the time metric already basically takes that into account so probably not necessary.  Players choose which level to play each time (no progression, no auto-loading the next puzzle when you finish one, unless maybe people want to turn that on).

This is significantly different from your setup, so I'm not sure if you'd be open to it, though.  If I can ever get the ruby running correctly, I might try making the changes myself and hosting it somewhere, though.

**Comment by fela** [comment]
I agree that once you finish level 15 the games stops being interesting. I guess the real solution would be to add harder levels, but I would need to rethink the level generation and difficulty estimation a bit.

If you look at the previous version of the game ( http://connecteverything.herokuapp.com/ ) it works pretty much as you describe. The problem is that the game became all about speed. Players kept generating levels until they got an easy looking one, then started solving as fast as they could and as soon as things seemed to get slower so unlikely to give a highscore they would start again. Thus I wanted to remove the speed factor, and the luck factor given by the fact that you only have to solve one grid. Only now it seems to be all about level 16, so still all about speed, oh well...
